### PR TITLE
Moving lb tags to beginning of line

### PR DESCRIPTION
**Pull request by HannimalCrackers**
Moved lb tags to beginning of line. Previously paragraph tag and some other tags were hanging in margin. Hanging has been preserved on those lines.

All inconsistent beginning margin spacing is preserved. Will raise an issue for standardization.

### CODE REVIEW

**Comment by HannimalCrackers** [comment]
Killing this pull request. Changes already made on master version.

**Comment by JonathanReeve** [comment]
Sorry to have beat you to this! I should've left a note in this 
issue
saying that I was going to do it. Describing the regex to you made 
me
just want to do it myself real quick.

Hopefully it was still a fun task, regardless?

**Comment by HannimalCrackers** [comment]
I'm glad you did! Yours was a better solution and I wasn't sure what the initial spacing should be. 

Yes, it was useful to learn about regex. I also gave me occasion to use git from the command line for the first time this morning in order to make my version match your latest. That was a good exercise too, though what ended up working for me was some "hack-hazard" mix of monkeying around in the command line, online and GitHub Desktop. Hopefully I didn't do anything dreadful to the master version in the process. I'm still not confident with git/github and sometimes wonder if I'm breaking things. Though I guess one can always revert, if I understand?

**Comment by JonathanReeve** [comment]
Nice. Yep, git won't let you break anything—that's the magic of it. Unless you run something with the `--force` flag. What I tend to do is create a new branch for every new feature, especially if there's the chance it might break something. Then moving back to the main branch is trivial. This is all part of the [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow.

**Comment by HannimalCrackers** [comment]
Thank you for the git flow link. So you create a develop branch, and then
branch off of the develop branch when working on features?

**Comment by JonathanReeve** [comment]
Yep. From what I've heard, the idea is to keep master always stable, and to merge into it from develop when you're sure it'll work. (Although I should really start doing that, myself—I have lots of broken master branches around.)

**Pull request closed without merging**
