### PR TITLE
Remove chapter prefixes from line numbers

### LINKED ISSUE #73: remove chapter prefixes from line numbers
This should be as easy as removing the first digit and then removing the leading zeroes.

### PR DESCRIPTION
**Pull request by pletcher**
Fixes #73

### CODE REVIEW

**Comment by pletcher** [comment]
Hmmm, not sure why the deploy/netfily check is failing. Any tips on what I should look into?

**Comment by JonathanReeve** [comment]
@pletcher, don't worry, I think the edition wasn't validating, anyway. I'll open an issue for fixing that. Thanks for the PR! Will review this soon.

**Comment by JonathanReeve** [comment]
So it looks like you removed the chapter prefixes from the actual line numbers, but the issue is actually labeled `XSLT`, so the goal was to remove the chapter prefixes from the transformed HTML, by changing the XSL file, not the original XML source. It's my mistake--I should've been more explicit about this in the issue. 

Basically the fix for #73 would be a line or two of XSL code that would automatically transform line numbers like `10005` in the XML source to `5` in the HTML, and `52267` to `2267`.  I think we'll keep the source line numbers the same, in case we need to be backwards-compatible with Gabler's edition. Also, this PR appears to have a lot of merge conflicts, so I couldn't merge this if I wanted to, without lots of manual fixing.

But thanks for this, anyway! And if you want to take a crack at the XSL, go for it!

**Comment by pletcher** [comment]
Ah, my bad — fixing the XSL makes a lot more sense, I should have realized that.

No sweat, though — this was just a short script to change these numbers; I think the same principle can be applied in the XSL.

(For future reference, the merge conflicts likely resulted from more recent updates to portrait.xml. Were this PR mergeable — admittedly, it is not — the fix would mostly consist of rebasing the repo locally and rerunning the aforementioned script — no need for a lot of manual tweaking. :) )

**Pull request closed without merging**
